---@meta

---@class component_acidlevel
---@field inst idk
---@field max idk
---@field current idk
---@field ignoreacidrainticks idk
---@field overrideacidraintick idk
---@field DoAcidRainDamageOnEquipped idk
---@field DoAcidRainRotOnAllItems idk
---@field DoAcidRainDamageOnHealth idk
---@field onstartisacidrainingfn idk
---@field onstopisacidrainingfn idk
---@field onstartisrainingfn idk
---@field onstopisrainingfn idk