---@meta

---@class component_amphibiouscreature
---@field inst idk
---@field tile idk
---@field tileinfo idk
---@field ontilechangefn idk
---@field in_water idk
---@field onwaterchangefn idk
---@field land_bank idk
---@field ocean_bank idk
---@field enterwaterfn idk
---@field exitwaterfn idk