---@meta

---@class component_boatcannonuser
---@field inst idk
---@field ismastersim idk
---@field aim_range_fx idk
---@field aiming_cannon idk
---@field task idk
---@field cannon_remove_callback idk
---@field classified idk
---@field ondetachclassified idk
---@field aimingcannon idk
---@field aimpos idk