---@meta

---@class component_boatrace_proximitychecker
---@field inst idk
---@field proximity_check_must_flags idk
---@field range idk
---@field found_delay idk
---@field stored_beacons idk
---@field _per_update_found_beacons idk
---@field on_found_beacon idk
---@field _race_update_task idk