---@meta

---@class component_colourtweener
---@field inst idk
---@field i_alpha idk
---@field t_alpha idk
---@field callback idk
---@field time idk
---@field timepassed idk
---@field tweening idk
---@field usewallupdate idk