---@meta

---@class component_deerherding
---@field inst idk
---@field herdhomelocation idk
---@field herdlocation idk
---@field herdheading idk
---@field herdspawner idk
---@field lastupdate idk
---@field grazetimer idk
---@field isgrazing idk
---@field keepheading idk
---@field grazing_time idk
---@field roaming_time idk
---@field disable_spooked idk
---@field valid_area_check idk
---@field force_keep_herd_together idk
---@field alerttargets idk
---@field isspooked idk