---@meta

---@class component_dryer
---@field product idk
---@field ingredient idk
---@field inst idk
---@field buildfile idk
---@field dried_buildfile idk
---@field foodtype idk
---@field remainingtime idk
---@field tasktotime idk
---@field task idk
---@field onstartdrying idk
---@field ondonedrying idk
---@field onharvest idk
---@field protectedfromrain idk
---@field watchingrain idk
---@field ingredientperish idk