---@meta

---@class component_emitter
---@field inst idk
---@field area_emitter idk
---@field config idk
---@field max_lifetime idk
---@field ground_height idk
---@field particles_per_tick idk
---@field num_particles_to_emit idk
---@field density_factor idk