---@meta

---@class component_grower
---@field inst idk
---@field crops idk
---@field level idk
---@field croppoints idk
---@field growrate idk
---@field cycles_left idk
---@field max_cycles_left idk
---@field isempty idk