---@meta

---@class component_heavyobstaclephysics
---@field currentradius idk
---@field physicsstate idk
---@field task idk
---@field ischaracterpassthrough idk
---@field inst idk
---@field maxradius idk
---@field issmall idk
---@field onphysicsstatechangedfn idk
---@field onchangetoitemfn idk
---@field onchangetoobstaclefn idk
---@field onstartfallingfn idk
---@field onstopfallingfn idk