---@meta

---@class component_hullhealth
---@field inst idk
---@field leak_point_count idk
---@field leak_radius idk
---@field leak_radius_variance idk
---@field leak_angle_variance idk
---@field leak_damage idk
---@field leak_indicators idk
---@field leak_indicators_dynamic idk
---@field small_leak_dmg idk
---@field med_leak_dmg idk
---@field max_health_damage idk
---@field hull_dmg idk
---@field selfdegradingtime idk
---@field currentdegradetime idk
---@field degradefx idk