---@meta

---@class component_mightiness
---@field inst idk
---@field max idk
---@field current idk
---@field rate idk
---@field drain_multiplier idk
---@field ratescale idk
---@field draining idk
---@field drain_delay idk
---@field ratemodifiers idk
---@field state idk
---@field invincible idk
---@field overmaxmax idk