---@meta

---@class component_oceanfishable
---@field inst idk
---@field rod idk
---@field rod_onremove idk
---@field catch_distance idk
---@field onsetrodfn idk
---@field oneatenfn idk
---@field onreelinginfn idk
---@field onreelinginpstfn idk
---@field makeprojectilefn idk
---@field stamina_def idk
---@field stamina idk
---@field is_struggling_state idk
---@field pending_is_struggling_state idk
---@field struggling_state_timer idk
---@field max_walk_speed idk
---@field max_run_speed idk