---@meta

---@class component_oceanfishingrod
---@field inst idk
---@field target idk
---@field casting_base idk
---@field casting_data idk
---@field default_projectile_prefab idk
---@field lure_base idk
---@field lure_data idk
---@field gettackledatafn idk
---@field target_onremove idk
---@field line_dist idk
---@field line_tension idk
---@field line_slack idk
---@field reeling_line_dist idk
---@field unreel_resistance idk
---@field oncastfn idk
---@field ondonefishing idk
---@field onhookedsomethingfn idk
---@field fishing_stats idk
---@field projectile_prefab idk
---@field default_lure_setup idk
---@field lure_setup idk
---@field fisher idk