---@meta

---@class component_oceantrawler
---@field inst idk
---@field lowered idk
---@field range idk
---@field nearbytrawlerrange idk
---@field nearbyshoalrange idk
---@field checkperiod idk
---@field catchfishchance idk
---@field sleepcheckperiod idk
---@field sleepcatchfishchance idk
---@field baitcatchfishmodifier idk
---@field task idk
---@field startsleeptime idk
---@field elapsedsleeptime idk
---@field overflowfish idk
---@field overflowescapepercent idk
---@field fishescaped idk