---@meta

---@class component_possessedaxe
---@field checkownertask idk
---@field currentowner idk
---@field oncontainerpickedup idk
---@field inst idk
---@field revert_prefab idk
---@field revert_uses idk
---@field revert_fx idk
---@field revert_time idk
---@field transform_fx idk
---@field player idk
---@field userid idk
---@field waittask idk
---@field waittotime idk
---@field onplayerdied idk
---@field onplayerremoved idk
---@field onplayerpossessedaxe idk
---@field onplayerjoined idk