---@meta

---@class component_shard_mermkingwatcher
---@field inst idk
---@field mermkings idk
---@field hasmermking idk
---@field tridents idk
---@field hastrident idk
---@field crowns idk
---@field hascrown idk
---@field pauldrons idk
---@field haspauldron idk
---@field OnMermKingExists idk
---@field OnMermKingTridentChanged idk
---@field OnMermKingCrownChanged idk
---@field OnMermKingPauldronsChanged idk
---@field OnHasMermKingDirty idk
---@field OnHasTridentDirty idk
---@field OnHasCrownDirty idk
---@field OnHasPauldronDirty idk