---@meta

---@class component_targettracker
---@field inst idk
---@field target idk
---@field timetracking idk
---@field pausetime idk
---@field onresettarget idk
---@field onpausefn idk
---@field onresumefn idk
---@field ontimeupdatefn idk
---@field shouldkeeptrackingfn idk
---@field _updating idk
---@field targetremovedfn idk
---@field lasttime idk