---@meta

---@class component_trophyscale
---@field inst idk
---@field type idk
---@field item_data idk
---@field compare_postfn idk
---@field onspawnitemfromdatafn idk
---@field onitemtakenfn idk
---@field takeitemtestfn idk
---@field accepts_items idk