---@meta

---@class component_uianim
---@field inst idk
---@field update_while_paused idk
---@field tint_t idk
---@field tint_whendone idk
---@field tint_start idk
---@field tint_dest idk
---@field tint_duration idk
---@field scale_t idk
---@field scale_whendone idk
---@field scale_start idk
---@field scale_dest idk
---@field scale_duration idk
---@field pos_t idk
---@field pos_whendone idk
---@field pos_start idk
---@field pos_dest idk
---@field pos_duration idk
---@field rot_t idk
---@field rot_whendone idk
---@field rot_start idk
---@field rot_dest idk
---@field rot_duration idk
---@field rot_infinite idk