---@meta

---@class component_upgrademoduleowner
---@field inst idk
---@field modules idk
---@field charge_level idk
---@field max_charge idk
---@field upgrade_cooldown idk
---@field onmoduleadded idk
---@field onmoduleremoved idk
---@field onallmodulespopped idk
---@field canupgradefn idk
---@field _last_upgrade_time idk