---@meta

---@class component_wagpunk_manager
---@field inst idk
---@field _enabled idk
---@field _updating idk
---@field machineGUIDS idk
---@field _activeplayers idk
---@field hintcount idk
---@field nexthinttime idk
---@field nextspawntime idk
---@field _currentnodeindex idk
---@field machinemarker idk
---@field bigjunk idk
---@field appliedfencerotationtransformation idk
---@field spawnedfences idk