---@meta

---@class component_walkableplatformplayer
---@field boatspeed idk
---@field boatpos idk
---@field boat_camera_enabled idk
---@field movement_prediction_enabled idk
---@field player_zooms idk
---@field player_zoom_task idk
---@field player_zoomout idk
---@field inst idk
---@field platform idk
---@field player_zoomed_out idk
---@field _doplatformcamerazoomdirty idk
---@field test_boat_speed_task idk