---@meta

---@class component_wateryprotection
---@field inst idk
---@field witherprotectiontime idk
---@field temperaturereduction idk
---@field addcoldness idk
---@field addwetness idk
---@field applywetnesstoitems idk
---@field extinguish idk
---@field extinguishheatpercent idk
---@field protection_dist idk
---@field ignoretags idk