---@meta

---@class component_weighable
---@field weight_percent idk
---@field inst idk
---@field type idk
---@field weight idk
---@field owner_userid idk
---@field owner_name idk
---@field prefab_override_owner idk
---@field min_weight idk
---@field max_weight idk