---@meta

---@class component_worldoverseer
---@field inst idk
---@field data idk
---@field _seenplayers idk
---@field _cycles idk
---@field _daytime idk
---@field _v2_seenplayers idk
---@field last_heartbeat_poll_time idk
---@field heartbeat_poll_counter idk