---@meta

---@class component_aoecharging
---@field inst idk
---@field allowriding idk
---@field chargeticks idk
---@field enable idk
---@field enabled idk
---@field ischarging idk
---@field ismastersim idk
---@field onchargedattackfn idk
---@field owner idk
---@field pingprefab idk
---@field refreshchargeticksfn idk
---@field reticule idk
---@field reticuleprefab idk
---@field syncdelay idk
