---@meta

---@class component_bloomness
---@field inst idk
---@field max idk
---@field level idk
---@field onlevelchangedfn idk
---@field timer idk
---@field stage_duration idk
---@field full_bloom_duration idk
---@field rate idk
---@field fertilizer idk
---@field is_blooming idk