---@meta

---@class component_boatmagnet
---@field inst idk
---@field boat idk
---@field beacon idk
---@field magnet_guid idk
---@field pair_tags idk
---@field canpairwithfn idk
---@field ClearEverything idk
---@field _setup_boat_task idk
---@field onpairedwithbeaconfn idk
---@field onunpairedwithbeaconfn idk
---@field beaconturnedonfn idk
---@field OnBeaconTurnedOn idk
---@field beaconturnedofffn idk
---@field OnBeaconTurnedOff idk
---@field OnInventoryBeaconLoaded idk