---@meta

---@class component_boattrail
---@field inst idk
---@field anim_idx idk
---@field effect_spawn_rate idk
---@field radius idk
---@field scale_x idk
---@field scale_z idk
---@field last_z idk
---@field total_distance_traveled idk
---@field last_x idk
---@field last_dir_x idk
---@field last_dir_z idk