---@meta

---@class component_boatcrew
---@field inst idk
---@field members idk
---@field membercount idk
---@field membertag idk
---@field loot_per_member idk
---@field captain idk
---@field tinkertargets idk
---@field gatherrange idk
---@field updaterange idk
---@field addmember idk
---@field removemember idk
---@field heading idk
---@field target idk
---@field flee idk
---@field status idk
---@field task idk
---@field _onmemberkilled idk
---@field membersearchtags idk