---@meta

---@class component_boatring
---@field inst idk
---@field rotationdirection idk
---@field rotate_speed idk
---@field max_rotate_speed idk
---@field updating idk
---@field boatbumpers idk
---@field rotators idk
---@field onrotationchanged idk