---@meta

---@class component_boatmagnetbeacon
---@field magnet idk
---@field magnet_guid idk
---@field _setup_boat_task idk
---@field inst idk
---@field turnedoff idk
---@field ispickedup idk
---@field boat idk
---@field magnet_must_tags idk
---@field magnet_cant_tags idk
---@field magnet_distance idk
---@field OnBoatRemoved idk
---@field OnBoatDeath idk