---@meta

---@class component_container_proxy
---@field inst idk
---@field ismastersim idk
---@field _cannotbeopened idk
---@field master idk
---@field openlist idk
---@field opencount idk
---@field onopenfn idk
---@field onclosefn idk
---@field _onmasteropenother idk
---@field _onmasterclose idk
---@field container_opener idk