---@meta

---@class component_deciduoustreeupdater
---@field inst idk
---@field monster idk
---@field monster_target idk
---@field last_monster_target idk
---@field last_attack_time idk
---@field root idk
---@field starttask idk
---@field drakespawntask idk
---@field ignitedrakespawntask idk
---@field sleeptask idk
---@field time_to_passive_drake idk
---@field num_passive_drakes idk
---@field monsterFreq idk
---@field monsterTime idk
---@field spawneddrakes idk
---@field numdrakes idk
---@field passive_drakes_spawned idk
---@field ignitenumdrakes idk