---@meta

---@class component_floater
---@field inst idk
---@field ismastersim idk
---@field size idk
---@field vert_offset idk
---@field xscale idk
---@field yscale idk
---@field zscale idk
---@field should_parent_effect idk
---@field do_bank_swap idk
---@field float_index idk
---@field swap_data idk
---@field showing_effect idk
---@field bob_percent idk
---@field splash idk
---@field _is_landed idk
---@field _erode_time idk
---@field is_obstable idk
---@field front_fx idk
---@field back_fx idk