---@meta

---@class component_freezefx
---@field inst idk
---@field level idk
---@field playingsound idk
---@field percent idk
---@field levels idk
---@field playignitesound idk
---@field bigignitesoundthresh idk
---@field usedayparamforsound idk
---@field current_radius idk
---@field isday idk