---@meta

---@class component_ghostlybond
---@field ghost idk
---@field inst idk
---@field ghost_prefab idk
---@field bondleveltimer idk
---@field bondlevelmaxtime idk
---@field paused idk
---@field bondlevel idk
---@field maxbondlevel idk
---@field _ghost_onremove idk
---@field _ghost_death idk
---@field externalbondtimemultipliers idk
---@field summoned idk
---@field notsummoned idk
---@field spawnghosttask idk
---@field pause idk