---@meta

---@class component_healthsyncer
---@field inst idk
---@field _status idk
---@field _healthpct idk
---@field corrosives idk
---@field _onremovecorrosive idk
---@field hots idk
---@field _onremovehots idk
---@field small_hots idk
---@field _onremovesmallhots idk