---@meta

---@class component_incrementalproducer
---@field inst idk
---@field producefn idk
---@field countfn idk
---@field maxcount idk
---@field maxcountfn idk
---@field increment idk
---@field incrementfn idk
---@field incrementdelay idk
---@field toproduce idk
---@field lastproduction idk