---@meta

---@class component_inventoryitem
---@field inst ent
---@field owner ent|nil
---@field canbepickedup idk
---@field canbepickedupalive idk
---@field onpickupfn idk
---@field isnew idk
---@field nobounce idk
---@field cangoincontainer idk
---@field canonlygoinpocket idk
---@field keepondeath idk
---@field atlasname idk
---@field imagename idk
---@field trappable idk
---@field sinks idk
---@field droprandomdir idk
---@field isacidsizzling idk
---@field pushlandedevents idk
---@field ondropfn fun(this:ent):...
---@field onactiveitemfn idk
---@field onputininventoryfn fun(this:ent,owner:ent):...
---@field is_landed idk
---@field foleysound string|nil # 拟音,填的是声音路径