---@meta

---@class component_lunarthrall_plantspawner
---@field _nextspawn idk
---@field waves_to_release idk
---@field _spawntask idk
---@field currentrift idk
---@field inst idk
---@field plantherds idk
---@field spawntasks idk
---@field targetedplants idk