---@meta

---@class component_mast
---@field inst idk
---@field is_sail_raised idk
---@field inverted idk
---@field sail_force idk
---@field has_speed idk
---@field boat idk
---@field rudder idk
---@field max_velocity_mod idk
---@field max_velocity idk
---@field rudder_turn_drag idk
---@field furlunits_max idk
---@field furlunits idk
---@field autounfurlunits idk
---@field furlers idk
---@field OnBoatRemoved idk
---@field OnBoatDeath idk
---@field _setup_boat_task idk
---@field boat_death idk
---@field is_sail_transitioning idk