---@meta

---@class component_meteorshower
---@field inst idk
---@field dt idk
---@field spawn_mod idk
---@field medium_remaining idk
---@field large_remaining idk
---@field retries_remaining idk
---@field task idk
---@field tasktotime idk
---@field level idk
---@field should_have_rock_moon_shell idk