---@meta

---@class component_minionspawner
---@field inst idk
---@field miniontype idk
---@field maxminions idk
---@field minionspawntime idk
---@field minions idk
---@field numminions idk
---@field distancemodifier idk
---@field onspawnminionfn idk
---@field onlostminionfn idk
---@field onminionattacked idk
---@field onminionattack idk
---@field spawninprogress idk
---@field nextspawninfo idk
---@field shouldspawn idk
---@field minionpositions idk
---@field validtiletypes idk
---@field freepositions idk
---@field _onminionattacked idk
---@field _onminionattack idk
---@field _onminiondeath idk
---@field _onminionremoved idk
---@field task idk