---@meta

---@class component_oceancolor
---@field inst idk
---@field start_color idk
---@field current_color idk
---@field end_color idk
---@field start_ocean_texture_blend idk
---@field current_ocean_texture_blend idk
---@field end_ocean_texture_blend idk
---@field lerp idk
---@field lerp_delay idk
---@field blend_delay idk
---@field blend_speed idk