---@meta

---@class component_playervision
---@field nightvision idk
---@field gogglevision idk
---@field nutrientsvision idk
---@field inst idk
---@field scrapmonolevision idk
---@field inspectaclesvision idk
---@field roseglassesvision idk
---@field ghostvision idk
---@field nightmarevision idk
---@field forcenightvision idk
---@field forcegogglevision idk
---@field forcenutrientsvision idk
---@field forcescrapmonolevision idk
---@field forceinspectaclesvision idk
---@field forceroseglassesvision idk
---@field overridecctable idk
---@field currentcctable idk
---@field currentccphasefn idk
---@field blendcctable idk
---@field forcednightvisionstack idk