---@meta

---@class component_playeravatardata
---@field inst idk
---@field hasdata idk
---@field allowemptyname idk
---@field allowburnt idk
---@field strings idk
---@field skins idk
---@field numbers idk
---@field equip idk
---@field unsupported_equips idk
---@field savestrings idk
---@field saveskins idk
---@field savenumbers idk
---@field saveequip idk