---@meta

---@class component_pointofinterest
---@field inst idk
---@field _showinghud idk
---@field shouldshowfn idk
---@field _updating idk
---@field height idk
---@field _TryStartingUpdating idk
---@field stand idk
---@field marker idk
---@field _removing idk
---@field loops idk
---@field ring1 idk
---@field ring2 idk