---@meta

---@class component_prophider
---@field inst idk
---@field hideupdate_duration idk
---@field hideupdate_variance idk
---@field propcreationfn idk
---@field onvisiblefn idk
---@field willunhidefn idk
---@field onunhidefn idk
---@field onhidefn idk
---@field prop idk
---@field counter idk
---@field hide_task idk
---@field hiding idk