---@meta

---@class component_prototyper
---@field inst idk
---@field trees idk
---@field on idk
---@field onturnon idk
---@field onturnoff idk
---@field doers idk
---@field restrictedtag idk
---@field onremovedoer idk