---@meta

---@class component_retrofitcavemap_anr
---@field inst idk
---@field requiresreset idk
---@field retrofit_artsandcrafts idk
---@field retrofit_heartoftheruins idk
---@field retrofit_heartoftheruins_respawnerfix idk
---@field retrofit_heartoftheruins_altars idk
---@field retrofit_heartoftheruins_caveholes idk
---@field retrofit_heartoftheruins_oldatriumfixup idk
---@field retrofit_heartoftheruins_statuechessrespawners idk
---@field retrofit_sacred_chest idk
---@field retrofit_archives_navmesh idk
---@field retrofit_nodeidtilemap_atriummaze idk
---@field retrofit_daywalker_content idk
---@field console_beard_turf_fix idk
---@field retrofit_acientarchives idk
---@field retrofit_acientarchives_fixes idk
---@field retrofit_dispencer_fixes idk