---@meta

---@class component_sentientaxe
---@field inst idk
---@field owner idk
---@field convo_task idk
---@field say_task idk
---@field warnlevel idk
---@field waslow idk
---@field _lastcarvingtalks idk
---@field _onbuilditem idk
---@field _onfinishedwork idk
---@field _onwereeaterchanged idk
---@field _onstartwereplayer idk
---@field _onstopwereplayer idk