---@meta

---@class component_spawner
---@field task idk
---@field inst idk
---@field child idk
---@field delay idk
---@field onoccupied idk
---@field onvacate idk
---@field spawnoffscreen idk
---@field nextspawntime idk
---@field queue_spawn idk
---@field retry_period idk
---@field _onchildkilled idk
---@field useexternaltimer idk
---@field externaltimerfinished idk
---@field starttimerfn idk
---@field stoptimerfn idk
---@field timertestfn idk
---@field spawn_in_water idk
---@field spawn_on_boats idk
---@field childname idk
---@field retryperiod idk