---@meta

---@class component_teamleader
---@field teamleadersearchtags idk
---@field teamsearchtags idk
---@field inst idk
---@field team_type idk
---@field min_team_size idk
---@field max_team_size idk
---@field team idk
---@field threat idk
---@field searchradius idk
---@field theta idk
---@field thetaincrement idk
---@field radius idk
---@field reverse idk
---@field timebetweenattacks idk
---@field attackinterval idk
---@field lifetime idk
---@field attack_grp_size idk
---@field chk_state idk
---@field maxchasetime idk
---@field chasetime idk