---@meta

---@class component_transformer
---@field queuedTransform idk
---@field queuedRevert idk
---@field inst idk
---@field transformPrefab idk
---@field objectData idk
---@field transformEvent idk
---@field transformEventTarget idk
---@field revertEvent idk
---@field revertEventTarget idk
---@field onTransform idk
---@field onRevert idk
---@field transformed idk
---@field transformOffScreen idk
---@field sleepRevertEvent idk
---@field sleepTransformEvent idk
---@field revertWorldEvent idk
---@field revertWorldEventValue idk
---@field transformWorldEvent idk
---@field transformWorldEventValue idk
---@field onLoadCheck idk