---@meta

---@class component_werebeast
---@field _task idk
---@field _reverttask idk
---@field inst idk
---@field onsetwerefn idk
---@field onsetnormalfn idk
---@field weretime idk
---@field triggerlimit idk
---@field triggeramount idk