---@meta

---@class component_winch
---@field inst idk
---@field onfullyloweredfn idk
---@field onfullyraisedfn idk
---@field onstartloweringfn idk
---@field onstartraisingfn idk
---@field unloadfn idk
---@field winch_ready idk
---@field line_length idk
---@field is_raising idk
---@field is_static idk
---@field raising_speed idk
---@field lowering_speed idk
---@field overridegetcurrentdepthfn idk