---@meta

---@class component_wisecracker
---@field inst idk
---@field time_in_lightstate idk
---@field inlight idk
---@field foodbuffname idk
---@field foodbuffpriority idk
---@field _repeltime idk
---@field fishbuffname idk
---@field fishbuffpriority idk