---@meta

---@class component_workable
---@field inst ent
---@field onwork idk
---@field onfinish idk
---@field workleft idk
---@field maxwork idk
---@field action idk
---@field savestate idk
---@field workable idk
---@field tough idk
---@field workmultiplierfn idk
---@field shouldrecoilfn idk
---@field onloadfn idk
---@field lastworktime idk