---@meta

---@class component_writeable # 书写组件
---@field inst ent #组件绑定的实体
---@field writeable_by_default boolean #是否默认可书写
---@field text string|nil #当前文本内容
---@field writer ent|nil #当前正在书写的玩家
---@field screen table|nil #书写界面对象
---@field onclosepopups fun(doer:ent)|nil #关闭弹窗回调
---@field generatorfn fun(inst:ent)|nil #文本生成函数
---@field automatic_description boolean #是否自动描述
---@field writeable_distance number #可书写距离
---@field onwritten fun(inst:ent, text:string, doer:ent)|nil #书写完成回调
---@field onwritingended fun(inst:ent)|nil #书写结束回调
---@field writer_netid string|nil #书写者网络ID
---@field writer_userid string|nil #书写者用户ID