---@meta

---@class component_yotb_sewer
---@field inst idk
---@field done idk
---@field targettime idk
---@field task idk
---@field product idk
---@field product_spoilage idk
---@field spoiledproduct idk
---@field spoiltime idk
---@field ingredient_prefabs idk