---@meta

---@class component_yotc_racecompetitor
---@field inst idk
---@field racestate idk
---@field race_start_point idk
---@field race_begun_fn idk
---@field race_finished_fn idk
---@field race_prize idk
---@field checkpoints idk
---@field race_distance idk
---@field checkpoint_timer idk
---@field forgetfulness idk
---@field stamina_max idk
---@field stamina_max_var idk
---@field stamina idk
---@field exhausted_time idk
---@field exhausted_time_var idk
---@field onnextcheckpointremove idk
---@field next_checkpoint idk
---@field start_race idk
---@field queuedstarttask idk
---@field race_over_fn idk
---@field walkspeechdone idk
---@field prev_checkpoint idk
---@field finished_first idk
---@field latestartertask idk
---@field recover_stamina_task idk