---@meta

---@class replica_sheltered
---@field _task idk
---@field _targetshade idk
---@field _shade idk
---@field inst idk
---@field _updating idk
---@field _shelterspeed idk
---@field _exposespeed idk
---@field _issheltered idk
---@field shade idk