---@meta

---@class replica_container
---@field inst ent
---@field _cannotbeopened idk
---@field _skipopensnd idk
---@field _skipclosesnd idk
---@field _isopen idk
---@field _numslots idk
---@field acceptsstacks idk
---@field usespecificslotsforitems idk
---@field issidewidget idk
---@field type idk
---@field widget idk
---@field itemtestfn idk
---@field priorityfn idk
---@field opentask idk
---@field openers idk
---@field opener idk
---@field classified idk
---@field _onitemget idk
---@field _onitemlose idk
---@field _onputininventory idk
---@field _ondropped idk
---@field _owner idk
---@field ondetachclassified idk
---@field ondetachopener idk