--- 任务的钥匙。决定了此任务可以连接到哪些其他任务。
KEYS = {
    NONE = 1,              -- 无
    PICKAXE = 2,           -- 镐 (可解锁: PIGGIFTS, SPIDERDENS, ROCKS)
    AXE = 3,               -- 斧 (可解锁: PIGGIFTS, TREES, SPIDERDENS, BEEHIVE, BASIC_COMBAT)
    GRASS = 4,             -- 草
    STONE = 5,             -- 石头
    WOOD = 6,              -- 木头
    MEAT = 7,              -- 肉 (可解锁: PIGGIFTS)
    PIGS = 8,              -- 猪 (可解锁: TREES, SPIDERDENS, MEAT, BASIC_COMBAT)
    FIRE = 9,              -- 火 (可解锁: TREES, SPIDERDENS)
    POOP = 10,             -- 粪便 (可解锁: FARM)
    WOOL = 11,             -- 羊毛
    FARM = 12,             -- 农场 (可解锁: MEAT)
    HONEY = 13,            -- 蜂蜜 (可解锁: SPIDERDENS, ADVANCED_COMBAT)
    GOLD = 14,             -- 黄金 (可解锁: ADVANCED_COMBAT)
    BEEHAT = 15,           -- 蜂帽 (可解锁: KILLERBEES)
    TRINKETS = 16,         -- 小玩具 (可解锁: PIGKING)
    HARD_WALRUS = 17,      -- 困难海象 (可解锁: HARD_MONSTERS_DEFEATED)
    HARD_SPIDERS = 18,     -- 困难蜘蛛 (可解锁: HARD_MONSTERS_DEFEATED)
    HARD_HOUNDS = 19,      -- 困难猎犬 (可解锁: HARD_MONSTERS_DEFEATED)
    HARD_MERMS = 20,       -- 困难鱼人 (可解锁: HARD_MONSTERS_DEFEATED)
    HARD_TENTACLES = 21,   -- 困难触手 (可解锁: HARD_MONSTERS_DEFEATED)
    WALRUS = 22,           -- 海象 (可解锁: MONSTERS_DEFEATED)
    SPIDERS = 23,          -- 蜘蛛 (可解锁: MEAT, MONSTERS_DEFEATED, SPIDERS_DEFEATED)
    HOUNDS = 24,           -- 猎犬 (可解锁: MONSTERS_DEFEATED)
    MERMS = 25,            -- 鱼人 (可解锁: MONSTERS_DEFEATED)
    GEARS = 26,            -- 齿轮
    CHESSMEN = 27,         -- 棋子 (可解锁: HARD_MONSTERS_DEFEATED, MONSTERS_DEFEATED)
    TENTACLES = 28,        -- 触手 (可解锁: MONSTERS_DEFEATED)
    TIER0 = 29,            -- 第0层 (可解锁: TIER0)
    TIER1 = 30,            -- 第1层 (可解锁: ONLYTIER1, TIER0, TIER1, ANYTIER, INNERTIER)
    TIER2 = 31,            -- 第2层 (可解锁: TIER1, TIER2, ANYTIER, INNERTIER)
    TIER3 = 32,            -- 第3层 (可解锁: TIER2, TIER3, ANYTIER, INNERTIER)
    TIER4 = 33,            -- 第4层 (可解锁: TIER3, TIER4, ANYTIER, OUTERTIER)
    TIER5 = 34,            -- 第5层 (可解锁: TIER4, TIER5, ANYTIER, OUTERTIER)
    TIER6 = 35,            -- 第6层 (可解锁: TIER5, ANYTIER, OUTERTIER)
    LIGHT = 36,            -- 光 (可解锁: LIGHT)
    FUNGUS = 37,           -- 真菌 (可解锁: FUNGUS)
    CAVE = 38,             -- 洞穴 (可解锁: CAVE)
    LABYRINTH = 39,        -- 迷宫 (可解锁: LABYRINTH)
    WILDS = 40,            -- 荒野 (可解锁: WILDS)
    RUINS = 41,            -- 废墟 (可解锁: RUINS)
    SACRED = 42,           -- 神圣的 (可解锁: SACRED)
    BADLANDS = 43,         -- 鸟不拉屎的地方
    ENTRANCE_INNER = 44,   -- 入口_内部 (可解锁: ENTRANCE_INNER)
    ENTRANCE_OUTER = 45,   -- 入口_外部 (可解锁: ENTRANCE_OUTER)
    MUSHROOM = 46,         -- 蘑菇 (可解锁: MUSHROOM)
    RABBIT = 47,           -- 兔人 (可解锁: RABBIT)
    PASSAGE = 48,          -- 通道 (可解锁: PASSAGE)
    AREA = 49,             -- 区域 (可解锁: AREA)
    CAVERN = 50,           -- 洞窟 (可解锁: CAVERN)
    SINKHOLE = 51,         -- 洞穴入口 (可解锁: SINKHOLE)
    BATS = 52,             -- 蝙蝠 (可解锁: BATS)
    EASY = 53,             -- 简单 (可解锁: EASY)
    MEDIUM = 54,           -- 中等 (可解锁: MEDIUM)
    HARD = 55,             -- 困难 (可解锁: HARD)
    BLUE = 56,             -- 蓝色 (可解锁: BLUE)
    RED = 57,              -- 红色 (可解锁: RED)
    GREEN = 58,            -- 绿色 (可解锁: GREEN)
    MOONMUSH = 59,         -- 月亮蘑菇 (可解锁: MOONMUSH)
    ARCHIVE = 60,          -- 档案馆 (可解锁: ARCHIVE)
    CENTIPEDE = 61,        -- 洞穴多足蜈蚣 (可解锁: CENTIPEDE)
    QUAGMIRE_GATEWAY = 62, -- 暴食-大门 (可解锁: QUAGMIRE_GATEWAY)
    QUAGMIRE_PARK_L1 = 63, -- 暴食-公园1级 (可解锁: QUAGMIRE_PARK_L1)
    QUAGMIRE_FOOD_L1 = 64, -- 暴食-食物1级 (可解锁: QUAGMIRE_FOOD_L1)
    QUAGMIRE_TRIBE = 65,   -- 暴食-部落 (可解锁: QUAGMIRE_TRIBE)
    QUAGMIRE_GIANT = 66,   -- 暴食-巨大 (可解锁: QUAGMIRE_GIANT)
    ISLAND_TIER1 = 67,     -- 岛屿第1层 (可解锁: ISLAND_TIER1)
    ISLAND_TIER2 = 68,     -- 岛屿第2层 (可解锁: ISLAND_TIER2)
    ISLAND_TIER3 = 69,     -- 岛屿第3层 (可解锁: ISLAND_TIER3)
    ISLAND_TIER4 = 70,     -- 岛屿第4层 (可解锁: ISLAND_TIER4)
}

--- 任务的锁。决定了哪些其他任务可以连接到此任务。
LOCKS = {
    NONE = 1,                    -- 无
    PIGGIFTS = 2,                -- 猪礼物 (可被 MEAT, AXE, PICKAXE 解锁)
    TREES = 3,                   -- 树 (可被 AXE, FIRE, PIGS 解锁)
    SPIDERDENS = 4,              -- 蜘蛛 (可被 PIGS, FIRE, AXE, PICKAXE, HONEY 解锁)
    ROCKS = 5,                   -- 岩石 (可被 PICKAXE 解锁)
    FARM = 6,                    -- 农场 (可被 POOP 解锁)
    MEAT = 7,                    -- 肉 (可被 SPIDERS, PIGS, FARM 解锁)
    BEEHIVE = 8,                 -- 蜂箱 (可被 AXE 解锁)
    KILLERBEES = 9,              -- 杀人蜂 (可被 BEEHAT 解锁)
    PIGKING = 10,                -- 养猪 (可被 TRINKETS 解锁)
    MONSTERS_DEFEATED = 11,      -- 怪物被打败了 (可被 WALRUS, SPIDERS, HOUNDS, MERMS, TENTACLES, CHESSMEN 解锁)
    HARD_MONSTERS_DEFEATED = 12, -- 困难怪物被打败了 (可被 HARD_WALRUS, HARD_SPIDERS, HARD_HOUNDS, HARD_MERMS, HARD_TENTACLES, CHESSMEN 解锁)
    SPIDERS_DEFEATED = 13,       -- 蜘蛛侠大获全胜 (可被 SPIDERS 解锁)
    BASIC_COMBAT = 14,           -- 基本战斗 (可被 AXE, PIGS 解锁)
    ADVANCED_COMBAT = 15,        -- 高级战斗 (可被 GOLD, HONEY 解锁)
    ONLYTIER1 = 16,              -- 仅第1层 (可被 TIER1 解锁)
    TIER0 = 17,                  -- 第0层 (可被 TIER0, TIER1 解锁)
    TIER1 = 18,                  -- 第1层 (可被 TIER1, TIER2 解锁)
    TIER2 = 19,                  -- 第2层 (可被 TIER2, TIER3 解锁)
    TIER3 = 20,                  -- 第3层 (可被 TIER3, TIER4 解锁)
    TIER4 = 21,                  -- 第4层 (可被 TIER4, TIER5 解锁)
    TIER5 = 22,                  -- 第5层 (可被 TIER5, TIER6 解锁)
    TIER6 = 23,                  -- 第6层
    ANYTIER = 24,                -- 任意层 (可被 TIER1, TIER2, TIER3, TIER4, TIER5, TIER6 解锁)
    INNERTIER = 25,              -- 内层 (可被 TIER1, TIER2, TIER3 解锁)
    OUTERTIER = 26,              -- 外层 (可被 TIER4, TIER5, TIER6 解锁)
    LIGHT = 27,                  -- 光 (可被 LIGHT 解锁)
    FUNGUS = 28,                 -- 真菌 (可被 FUNGUS 解锁)
    CAVE = 29,                   -- 洞穴 (可被 CAVE 解锁)
    LABYRINTH = 30,              -- 迷宫 (可被 LABYRINTH 解锁)
    WILDS = 31,                  -- 荒野 (可被 WILDS 解锁)
    RUINS = 32,                  -- 废墟 (可被 RUINS 解锁)
    SACRED = 33,                 -- 神圣的 (可被 SACRED 解锁)
    BADLANDS = 34,               -- 鸟不拉屎的地方
    HOUNDS = 35,                 -- 猎犬
    ENTRANCE_INNER = 36,         -- 入口_内部 (可被 ENTRANCE_INNER 解锁)
    ENTRANCE_OUTER = 37,         -- 入口_外部 (可被 ENTRANCE_OUTER 解锁)
    MUSHROOM = 38,               -- 蘑菇 (可被 MUSHROOM 解锁)
    RABBIT = 39,                 -- 兔人 (可被 RABBIT 解锁)
    PASSAGE = 40,                -- 通道 (可被 PASSAGE 解锁)
    AREA = 41,                   -- 区域 (可被 AREA 解锁)
    CAVERN = 42,                 -- 洞窟 (可被 CAVERN 解锁)
    SINKHOLE = 43,               -- 洞穴入口 (可被 SINKHOLE 解锁)
    BATS = 44,                   -- 蝙蝠 (可被 BATS 解锁)
    EASY = 45,                   -- 简单 (可被 EASY 解锁)
    MEDIUM = 46,                 -- 中等 (可被 MEDIUM 解锁)
    HARD = 47,                   -- 困难 (可被 HARD 解锁)
    BLUE = 48,                   -- 蓝色 (可被 BLUE 解锁)
    RED = 49,                    -- 红色 (可被 RED 解锁)
    GREEN = 50,                  -- 绿色 (可被 GREEN 解锁)
    MOONMUSH = 51,               -- 月亮蘑菇 (可被 MOONMUSH 解锁)
    ARCHIVE = 52,                -- 档案馆 (可被 ARCHIVE 解锁)
    CENTIPEDE = 53,              -- 洞穴多足蜈蚣 (可被 CENTIPEDE 解锁)
    QUAGMIRE_GATEWAY = 54,       -- 暴食-大门 (可被 QUAGMIRE_GATEWAY 解锁)
    QUAGMIRE_PARK_L1 = 55,       -- 暴食-公园1级 (可被 QUAGMIRE_PARK_L1 解锁)
    QUAGMIRE_FOOD_L1 = 56,       -- 暴食-食物1级 (可被 QUAGMIRE_FOOD_L1 解锁)
    QUAGMIRE_TRIBE = 57,         -- 暴食-部落 (可被 QUAGMIRE_TRIBE 解锁)
    QUAGMIRE_GIANT = 58,         -- 暴食-巨大 (可被 QUAGMIRE_GIANT 解锁)
    ISLAND_TIER1 = 59,           -- 岛屿第1层 (可被 ISLAND_TIER1 解锁)
    ISLAND_TIER2 = 60,           -- 岛屿第2层 (可被 ISLAND_TIER2 解锁)
    ISLAND_TIER3 = 61,           -- 岛屿第3层 (可被 ISLAND_TIER3 解锁)
    ISLAND_TIER4 = 62,           -- 岛屿第4层 (可被 ISLAND_TIER4 解锁)
}

---@enum WORLD_TILES # 地皮类型和编号
WORLD_TILES = {
    INVALID = 65535,             -- 虚空 (地图边角外)
    IMPASSABLE = 1,              -- 云海
    ROAD = 2,                    -- 卵石路
    ROCKY = 3,                   -- 岩石地皮
    DIRT = 4,                    -- 泥土 (叉掉后的空地皮)
    SAVANNA = 5,                 -- 热带草原地皮
    GRASS = 6,                   -- 长草地皮
    FOREST = 7,                  -- 森林地皮
    MARSH = 8,                   -- 沼泽地皮
    WEB = 9,                     -- 蜘蛛网 (黑色铲掉变无)
    WOODFLOOR = 10,              -- 木地板
    CARPET = 11,                 -- 地毯地板
    CHECKER = 12,                -- 棋盘地板
    CAVE = 13,                   -- 鸟粪地皮
    FUNGUS = 14,                 -- 真菌地皮
    SINKHOLE = 15,               -- 黏滑地皮 (洞穴草地)
    UNDERROCK = 16,              -- 洞穴岩石地皮
    MUD = 17,                    -- 泥泞地皮
    BRICK = 18,                  -- 远古地面
    BRICK_GLOW = 19,             -- 仿远古地面
    TILES = 20,                  -- 远古瓷砖
    TILES_GLOW = 21,             -- 仿远古瓷砖
    TRIM = 22,                   -- 远古砖雕
    TRIM_GLOW = 23,              -- 仿远古砖雕
    FUNGUSRED = 24,              -- 红真菌地皮
    FUNGUSGREEN = 25,            -- 绿真菌地皮
    DECIDUOUS = 30,              -- 落叶林地皮
    DESERT_DIRT = 31,            -- 沙漠地皮
    SCALE = 32,                  -- 龙鳞地皮
    LAVAARENA_FLOOR = 33,        -- 熔炉地板 (炸档)
    LAVAARENA_TRIM = 34,         -- 熔炉瓷砖 (炸档)
    QUAGMIRE_PEATFOREST = 35,    -- 暴食石油沼泽 (森林)
    QUAGMIRE_PARKFIELD = 36,     -- 暴食糖木草地
    QUAGMIRE_PARKSTONE = 37,     -- 暴食石面盐渍
    QUAGMIRE_GATEWAY = 38,       -- 暴食草地
    QUAGMIRE_SOIL = 39,          -- 暴食耕地
    QUAGMIRE_CITYSTONE = 41,     -- 暴食石面城市
    PEBBLEBEACH = 42,            -- 岩石海滩地皮
    METEOR = 43,                 -- 月球环形山地皮
    SHELLBEACH = 44,             -- 贝壳海滩地皮
    ARCHIVE = 45,                -- 远古石刻
    FUNGUSMOON = 46,             -- 变异真菌地皮
    FARMING_SOIL = 47,           -- 耕地
    FUNGUSMOON_NOISE = 120,      -- 真菌月亮噪音
    METEORMINE_NOISE = 121,      -- 陨石矿噪音
    METEORCOAST_NOISE = 122,     -- 陨石海岸噪音
    DIRT_NOISE = 123,            -- 泥土噪音
    ABYSS_NOISE = 124,           -- 深渊噪音
    GROUND_NOISE = 125,          -- 地面噪音
    CAVE_NOISE = 126,            -- 洞穴噪音
    FUNGUS_NOISE = 127,          -- 真菌噪音
    UNDERGROUND = 128,           -- 地下
    WALL_ROCKY = 151,            -- 岩石墙壁
    WALL_DIRT = 152,             -- 泥土墙
    WALL_MARSH = 153,            -- 沼泽墙壁
    WALL_CAVE = 154,             -- 洞穴墙壁
    WALL_FUNGUS = 155,           -- 真菌墙壁
    WALL_SINKHOLE = 156,         -- 黏滑墙壁
    WALL_MUD = 157,              -- 泥泞墙壁
    WALL_TOP = 158,              -- 顶部墙壁
    WALL_WOOD = 159,             -- 木墙壁
    WALL_HUNESTONE = 160,        -- 蜂蜜墙壁
    WALL_HUNESTONE_GLOW = 161,   -- 发光的蜂蜜墙壁
    WALL_STONEEYE = 162,         -- 石头眼墙壁
    WALL_STONEEYE_GLOW = 163,    -- 发光的石头眼墙壁
    FAKE_GROUND = 200,           -- 假地面
    OCEAN_START = 201,           -- 海洋起点
    OCEAN_COASTAL = 201,         -- 浅海 (可放码头)
    OCEAN_COASTAL_SHORE = 202,   -- 浅海海岸
    OCEAN_SWELL = 203,           -- 中海
    OCEAN_ROUGH = 204,           -- 深海
    OCEAN_BRINEPOOL = 205,       -- 盐池
    OCEAN_BRINEPOOL_SHORE = 206, -- 盐池海岸 (盐矿区)
    OCEAN_HAZARDOUS = 207,       -- 危险海洋 (沉船区)
    OCEAN_WATERLOG = 208,        -- 水池 (水中木)
    OCEAN_END = 247,             -- 海洋终点
    MONKEY_DOCK = 258,           -- 码头套装
    OCEAN_ICE = 259,             -- 冰块浮岛
    BEARD_RUG = 265,             -- 胡须地毯地皮
}