---@meta

---@class widget_animspinner: widget_spinner
---@field fganim idk #
---@field arrow_scale idk #
---@field old_symbol idk #
---@field bank idk #
---@field anim idk #
---@field skin idk #
---@field new_anim idk #
---@field updating idk #
---@field selectedIndex idk #
