---@meta

---@class widget_announcementwidget: widget_widget
---@field root idk #
---@field text idk #
---@field icon idk #
---@field font idk #
---@field size idk #
---@field colour idk #
---@field announce_type idk #
---@field lifetime idk #
---@field fadetime idk #
