---@meta

---@class widget_badge: widget_widget
---@field owner idk #
---@field percent idk #
---@field pulse idk #
---@field warning idk #
---@field warningstarted idk #
---@field warningdelaytask idk #
---@field anim idk #
---@field backing idk #
---@field circular_meter idk #
---@field circleframe idk #
---@field dont_animate_circleframe idk #
---@field iconbuild idk #
---@field underNumber idk #
---@field num idk #
