---@meta

---@class widget_characterselect: widget_widget
---@field owner idk #
---@field OnPortraitSelected idk #
---@field proot idk #
---@field repeat_time idk #
---@field heroportrait idk #
---@field leftsmallportrait idk #
---@field characterIdx idk #
---@field leftportrait idk #
---@field rightportrait idk #
---@field rightsmallportrait idk #
---@field portrait_shadow idk #
---@field characters idk #
---@field left_arrow idk #
---@field right_arrow idk #
---@field herocharacter idk #
