---@meta

---@class widget_chatqueue: widget_widget
---@field owner idk #
---@field chat_queue_data idk #
---@field widget_rows idk #
---@field chat_font idk #
---@field chat_size idk #
---@field chat_height idk #
---@field user_width idk #
---@field user_max_chars idk #
---@field message_width idk #
---@field message_max_chars idk #
