---@meta

---@class widget_containerwidget: widget_widget
---@field open idk #
---@field inv idk #
---@field owner idk #
---@field slotsperrow idk #
---@field bganim idk #
---@field bgimage idk #
---@field isopen idk #
---@field button idk #
---@field onitemlosefn idk #
---@field onitemgetfn idk #
---@field onrefreshfn idk #
---@field container ent|nil #
---@field should_close_widget idk #
