---@meta

---@class widget_countdownbeta: widget_widget
---@field bg idk #
---@field daysuntiltext idk #
---@field image idk #
---@field title idk #
---@field title2 idk #
---@field reveal_image idk #
---@field smoke idk #
---@field button idk #
---@field focus_forward idk #
