---@meta

---@class widget_craftslot: widget_widget
---@field owner idk #
---@field atlas idk #
---@field bgimage idk #
---@field tile idk #
---@field fgimage idk #
---@field lightbulbimage idk #
---@field isquagmireshop idk #
---@field recipepopup idk #
---@field down idk #
---@field recipe_held idk #
---@field last_recipe_click idk #
---@field recipename idk #
---@field recipe idk #
---@field recipe_skins idk #
---@field canbuild idk #
---@field locked idk #
---@field open idk #
