---@meta

---@class widget_dressupavatarpopup: widget_playeravatarpopup
---@field frame idk #
---@field frame_bg idk #
---@field title idk #
---@field title2 idk #
---@field horizontal_line1 idk #
---@field body_image idk #
---@field horizontal_line2 idk #
---@field hand_image idk #
---@field horizontal_line3 idk #
---@field legs_image idk #
---@field horizontal_line4 idk #
---@field feet_image idk #
---@field close_button idk #
---@field started idk #
---@field out_pos idk #
---@field in_pos idk #
---@field settled idk #
---@field current_speed idk #
---@field currentcharacter idk #
---@field player_name idk #
---@field dressed idk #
