---@meta

---@class widget_fumeover: widget_widget
---@field _updateperiod idk #
---@field _updatetask idk #
---@field owner idk #
---@field over idk #
---@field top idk #
---@field debuffs idk #
---@field _onremovedebuff idk #
---@field corrosives idk #
---@field _onremovecorrosive idk #
