---@meta

---@class widget_healthbadge: widget_badge
---@field topperanim idk #
---@field circleframe2 idk #
---@field sanityarrow idk #
---@field effigyanim idk #
---@field effigy idk #
---@field effigybreaksound idk #
---@field corrosives idk #
---@field _onremovecorrosive idk #
---@field hots idk #
---@field _onremovehots idk #
---@field small_hots idk #
---@field _onremovesmallhots idk #
---@field acidsizzling idk #
---@field arrowdir idk #
