---@meta

---@class widget_hoverer: widget_widget
---@field owner idk #
---@field isFE idk #
---@field default_text_pos idk #
---@field text idk #
---@field secondarytext idk #
---@field lastStr idk #
---@field strFrames idk #
---@field str idk #
---@field secondarystr idk #
---@field followhandler idk #
