---@meta

---@class widget_hudcompass: widget_widget
---@field owner idk #
---@field isattached idk #
---@field bg idk #
---@field needle idk #
---@field displayheading idk #
---@field currentheading idk #
---@field offsetheading idk #
---@field forceperdegree idk #
---@field headingvel idk #
---@field damping idk #
---@field easein idk #
---@field currentcompass idk #
---@field isopen idk #
---@field istransitioning idk #
---@field wantstoclose idk #
---@field ontransout idk #
---@field ontransin idk #
