---@meta

---@class widget_inspectaclesover: widget_uianim
---@field owner idk #
---@field tz idk #
---@field pinger idk #
---@field pingtask idk #
---@field BUFFEROVERRIDES idk #
---@field PingerStop idk #
---@field shown idk #
---@field hidetask idk #
