---@meta

---@class widget_itemslot: widget_widget
---@field owner idk #
---@field bgimage idk #
---@field tile idk #
---@field highlight_scale idk #
---@field base_scale idk #
---@field highlight idk #
---@field big idk #
---@field ontilechangedfn idk #
---@field bgimage2 idk #
---@field label idk #
