---@meta

---@class widget_loadingwidget: widget_widget
---@field forceShowNextFrame idk #
---@field is_enabled idk #
---@field image_random idk #
---@field bg idk #
---@field root_classic idk #
---@field active_image idk #
---@field vig idk #
---@field loading_widget idk #
---@field elipse_state idk #
---@field cached_fade_level idk #
---@field step_time idk #
