---@meta

---@class widget_menu: widget_widget
---@field offset idk #
---@field style idk #
---@field textSize idk #
---@field items idk #
---@field horizontal idk #
---@field wrap_focus idk #
---@field controller_id idk #
---@field last_focused_index idk #
