---@meta

---@class widget_miasmaover: widget_widget
---@field owner idk #
---@field minscale idk #
---@field maxscale idk #
---@field bg idk #
---@field letterbox idk #
---@field clouds idk #
---@field ambientlighting idk #
---@field camera idk #
---@field brightness idk #
---@field blind idk #
---@field blindto idk #
---@field blindtime idk #
---@field fade idk #
---@field fadeto idk #
---@field fadetime idk #
---@field alpha idk #
