---@meta

---@class widget_playerlist: widget_widget
---@field owner idk #
---@field proot idk #
---@field numPlayers idk #
---@field focus_forward idk #
---@field player_list idk #
---@field title idk #
---@field bg idk #
---@field upper_horizontal_line idk #
---@field right_line idk #
---@field left_line idk #
---@field lower_horizontal_line idk #
---@field players_number idk #
---@field list_root idk #
---@field row_root idk #
---@field player_widgets idk #
---@field scroll_list idk #
