---@meta

---@class widget_playerdeathnotification: widget_widget
---@field owner idk #
---@field closing idk #
---@field root idk #
---@field bg idk #
---@field close_button_root idk #
---@field close_button idk #
---@field msgroot idk #
---@field avatar idk #
---@field avatar_message idk #
---@field revive_message idk #
---@field regen_countdown_message idk #
---@field regen_root idk #
---@field regen_button idk #
---@field default_focus idk #
---@field regen_text idk #
---@field seperator idk #
---@field target_y idk #
---@field _oncontinuefrompause idk #
---@field reset_hold_time idk #
---@field regen_confirm idk #
---@field started idk #
---@field time_sound_count idk #
---@field _onworldresettick idk #
---@field _lastshowntime idk #
