---@meta

---@class widget_quagmire_recipepopup: widget_widget
---@field smallfonts idk #
---@field hud_atlas idk #
---@field bg idk #
---@field contents idk #
---@field name idk #
---@field desc idk #
---@field button idk #
---@field recipe_held idk #
---@field last_recipe_click idk #
---@field ingredient_backing idk #
---@field ingredient idk #
---@field teaser idk #
---@field num_ingredients idk #
---@field recipe idk #
---@field owner idk #
