---@meta

---@class widget_radiobuttons: widget_widget
---@field options idk #
---@field width idk #
---@field height idk #
---@field buttonsettings idk #
---@field horizontal_layout idk #
---@field onbuttonconstruct idk #
---@field buttonwidgets idk #
---@field selectedIndex idk #
---@field focus_forward idk #
---@field onchangedfn idk #
