---@meta

---@class widget_secondarystatusdisplays: widget_widget
---@field modetask idk #
---@field onmodulesdirty idk #
---@field onpopallmodulesevent idk #
---@field onupgrademodulesenergylevelupdated idk #
---@field owner idk #
---@field column1 idk #
---@field isghostmode idk #
---@field side_inv idk #
---@field upgrademodulesdisplay idk #
