---@meta

---@class widget_skilltreetoast: widget_widget
---@field controls idk #
---@field owner idk #
---@field root idk #
---@field tab_gift idk #
---@field controller_hide idk #
---@field craft_hide idk #
---@field opened idk #
---@field hud_focus idk #
---@field enabled idk #
---@field controller_help idk #
