---@meta

---@class widget_skinspuppet_beefalo: widget_button
---@field anim idk #
---@field animstate idk #
---@field currentanimbank idk #
---@field current_idle_anim idk #
---@field default_build idk #
---@field last_skins idk #
---@field shadow idk #
---@field prefabname idk #
