---@meta

---@class widget_skincollector: widget_widget
---@field mini_game idk #
---@field start_text idk #
---@field root idk #
---@field innkeeper idk #
---@field speech_bubble idk #
---@field text idk #
---@field hand idk #
---@field last_speech_time idk #
---@field num_items idk #
---@field exit_callback idk #
---@field text_string idk #
---@field display_text_time idk #
---@field talking idk #
---@field sound_started idk #
---@field sleeped idk #
---@field intro_done idk #
