---@meta

---@class widget_snapshottab: widget_widget
---@field snapshot_page idk #
---@field left_line idk #
---@field save_slot idk #
---@field session_id idk #
---@field online_mode idk #
---@field multi_level idk #
---@field use_cluster_path idk #
---@field cb idk #
---@field snapshots idk #
---@field slotsnaps idk #
---@field default_focus idk #
---@field focus_forward idk #
---@field snapshot_page_scroll_root idk #
---@field snapshot_page_row_root idk #
---@field snapshot_widgets idk #
---@field snapshot_scroll_list idk #
