---@meta

---@class widget_spinner: widget_widget
---@field width idk #
---@field height idk #
---@field lean idk #
---@field control_prev idk #
---@field control_next idk #
---@field atlas idk #
---@field textures idk #
---@field textinfo idk #
---@field editable idk #
---@field options idk #
---@field selectedIndex idk #
---@field textsize idk #
---@field arrow_scale idk #
---@field textcolour idk #
---@field background idk #
---@field leftimage idk #
---@field rightimage idk #
---@field fgimage idk #
---@field text idk #
---@field updating idk #
---@field changing idk #
---@field changed_image idk #
---@field SetHasModification idk #
---@field mute_negative_sound idk #
---@field left_hint idk #
---@field right_hint idk #
---@field hints_enabled idk #
---@field saved_idx idk #
---@field onclick idk #
---@field onchangedfn idk #
---@field enableWrap idk #
