---@meta

---@class widget_statusdisplays_lavaarena: widget_widget
---@field modetask idk #
---@field onhealthdelta idk #
---@field healthmax idk #
---@field queuedhealthmax idk #
---@field onpethealthdirty idk #
---@field owner idk #
---@field heart idk #
---@field healthpenalty idk #
---@field isghostmode idk #
---@field craft_hide idk #
---@field visiblemode idk #
---@field pet_heart idk #
