---@meta

---@class widget_tab: widget_widget
---@field group idk #
---@field atlas idk #
---@field icon_atlas idk #
---@field selectfn idk #
---@field deselectfn idk #
---@field collapsed idk #
---@field imnormal idk #
---@field imselected idk #
---@field imhighlight idk #
---@field imalthighlight idk #
---@field basescale idk #
---@field selected idk #
---@field highlighted idk #
---@field bg idk #
---@field icon idk #
---@field overlay idk #
---@field disable_scaling idk #
---@field overlay_scaling idk #
---@field overlayshow idk #
---@field highlightnum idk #
---@field alternatehighlighted idk #
