---@meta

---@class widget_tilebg: widget_widget
---@field atlas idk #
---@field tileim idk #
---@field sepim idk #
---@field endim idk #
---@field horizontal idk #
---@field numtiles idk #
---@field w idk #
---@field h idk #
---@field slotpos idk #
---@field stepsize idk #
---@field length idk #
---@field bgs idk #
---@field seps idk #
