---@meta

---@class widget_votedialog: widget_widget
---@field owner idk #
---@field controller_mode idk #
---@field controller_hint_delay idk #
---@field controllervotescreen idk #
---@field controllerselection idk #
---@field controllerscaling idk #
---@field root idk #
---@field dialogroot idk #
---@field bg idk #
---@field starter idk #
---@field title idk #
---@field timer idk #
---@field instruction idk #
---@field left_bar idk #
---@field right_bar idk #
---@field options_root idk #
---@field num_options idk #
---@field buttons idk #
---@field labels_desc idk #
---@field start_root_y_pos idk #
---@field target_root_y_pos idk #
---@field current_root_y_pos idk #
---@field current_speed idk #
---@field started idk #
---@field settled idk #
---@field canvote idk #
