---@meta

---@class widget_wandaagebadge: widget_badge
---@field rate_time idk #
---@field warning_precent idk #
---@field health_precent idk #
---@field year_hand idk #
---@field days_hand idk #
---@field effigyanim idk #
---@field effigy idk #
---@field effigybreaksound idk #
---@field corrosives idk #
---@field _onremovecorrosive idk #
---@field playing_pulse_loop idk #
---@field acidsizzling idk #
---@field hots idk #
---@field _onremovehots idk #
---@field healthpenalty idk #
---@field pulsing idk #
---@field turnofftask idk #
