---@meta

---@class widget_wheel: widget_widget
---@field owner idk #
---@field selected_label idk #
---@field items idk #
---@field isopen idk #
---@field iscontroller idk #
---@field ignoreleftstick idk #
---@field ignorerightstick idk #
---@field cur_cell_index idk #
---@field activeitems idk #
---@field activeitemscount idk #
