---@meta

---@class widget_wordpredictionwidget: widget_widget
---@field word_predictor idk #
---@field text_edit idk #
---@field enter_complete idk #
---@field tab_complete idk #
---@field sizey idk #
---@field max_width idk #
---@field backing idk #
---@field prediction_root idk #
---@field starting_offset_x idk #
---@field start_index idk #
---@field scrollleft_btn idk #
---@field scrollright_btn idk #
---@field expanded idk #
---@field expand_btn idk #
---@field active_prediction_btn idk #
---@field prediction_btns idk #
