---@meta

---@class widget_writeablewidget: widget_screen
---@field owner idk #
---@field writeable idk #
---@field config idk #
---@field isopen idk #
---@field _scrnh idk #
---@field scalingroot idk #
---@field root idk #
---@field black idk #
---@field bganim idk #
---@field bgimage idk #
---@field title idk #
---@field edit_text_bg idk #
---@field edit_text idk #
---@field buttons idk #
---@field menu idk #
---@field default_focus idk #
